function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "CollectPhaseSpaceDataJetson"};
	this.sidHashMap["CollectPhaseSpaceDataJetson"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "CollectPhaseSpaceDataJetson:83"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:83"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "CollectPhaseSpaceDataJetson:94"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:94"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Compare To Zero1"] = {sid: "CollectPhaseSpaceDataJetson:83"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:83"] = {rtwname: "<Root>/Compare To Zero1"};
	this.rtwnameHashMap["<Root>/Data Type Conversion"] = {sid: "CollectPhaseSpaceDataJetson:122"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:122"] = {rtwname: "<Root>/Data Type Conversion"};
	this.rtwnameHashMap["<Root>/Demux1"] = {sid: "CollectPhaseSpaceDataJetson:93"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:93"] = {rtwname: "<Root>/Demux1"};
	this.rtwnameHashMap["<Root>/Enabled Subsystem1"] = {sid: "CollectPhaseSpaceDataJetson:94"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:94"] = {rtwname: "<Root>/Enabled Subsystem1"};
	this.rtwnameHashMap["<Root>/Mux1"] = {sid: "CollectPhaseSpaceDataJetson:102"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:102"] = {rtwname: "<Root>/Mux1"};
	this.rtwnameHashMap["<Root>/Stream PhaseSpace to Platform"] = {sid: "CollectPhaseSpaceDataJetson:49"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:49"] = {rtwname: "<Root>/Stream PhaseSpace to Platform"};
	this.rtwnameHashMap["<Root>/UDP Send1"] = {sid: "CollectPhaseSpaceDataJetson:124"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:124"] = {rtwname: "<Root>/UDP Send1"};
	this.rtwnameHashMap["<Root>/UDP Send2"] = {sid: "CollectPhaseSpaceDataJetson:125"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:125"] = {rtwname: "<Root>/UDP Send2"};
	this.rtwnameHashMap["<Root>/UDP Send3"] = {sid: "CollectPhaseSpaceDataJetson:123"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:123"] = {rtwname: "<Root>/UDP Send3"};
	this.rtwnameHashMap["<Root>/UDP Send4"] = {sid: "CollectPhaseSpaceDataJetson:120"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:120"] = {rtwname: "<Root>/UDP Send4"};
	this.rtwnameHashMap["<S1>/u"] = {sid: "CollectPhaseSpaceDataJetson:83:1"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:83:1"] = {rtwname: "<S1>/u"};
	this.rtwnameHashMap["<S1>/Compare"] = {sid: "CollectPhaseSpaceDataJetson:83:2"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:83:2"] = {rtwname: "<S1>/Compare"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "CollectPhaseSpaceDataJetson:83:3"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:83:3"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/y"] = {sid: "CollectPhaseSpaceDataJetson:83:5"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:83:5"] = {rtwname: "<S1>/y"};
	this.rtwnameHashMap["<S2>/In1"] = {sid: "CollectPhaseSpaceDataJetson:95"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:95"] = {rtwname: "<S2>/In1"};
	this.rtwnameHashMap["<S2>/Enable"] = {sid: "CollectPhaseSpaceDataJetson:96"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:96"] = {rtwname: "<S2>/Enable"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "CollectPhaseSpaceDataJetson:97"};
	this.sidHashMap["CollectPhaseSpaceDataJetson:97"] = {rtwname: "<S2>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
